server:
  port: 9191

spring:
  application:
    name: legal-ease-backend
  datasource:
    url: jdbc:postgresql://localhost:5435/legal-ease
    username: postgres
    password: fPsdg-fergerngLNF
    driver-class-name: org.postgresql.Driver
  hikari:
    maximum-pool-size: 100
    minimum-idle: 10
    idle-timeout: 30000
    max-lifetime: 1800000
    connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    username: example@gmail.com
    password: dssg nfoy sias moik
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  liquibase:
    change-log: classpath:liquibase/master.xml
    enabled: true
    drop-first: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  jwt:
    access-secret: 06d701201a0cec185ac8232ad254e5e52b7000828740253ba228bf3d50f6aec7
    refresh-secret: 1f9b840af387532bd295de7df4962e11edcb619954305adb36e30ea7c20a42c7
    issuer: att_system
    access-exp-min: 30
    refresh-exp-min: 1440
  task:
    execution:
      pool:
        core-size: 2
        max-size: 5
        queue-capacity: 100
      thread-name-prefix: email-async-

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    show-details: always

