server:
  port: 9191

spring:
  application:
    name: legal-ease-backend

  datasource:
    url: jdbc:postgresql://localhost:5435/legal-ease
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  hikari:
    maximum-pool-size: 20
    minimum-idle: 5
    idle-timeout: 30000
    max-lifetime: 1800000
    connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  liquibase:
    change-log: classpath:liquibase/master.xml
    enabled: true

  mail:
    host: smtp.gmail.com
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  task:
    execution:
      pool:
        core-size: 2
        max-size: 5
        queue-capacity: 100
      thread-name-prefix: email-async-

  jwt:
    access-secret: ${SPRING_JWT_ACCESS_SECRET:06d701201a0cec185ac8232ad254e5e52b7000828740253ba228bf3d50f6aec7}
    refresh-secret: ${SPRING_JWT_REFRESH_SECRET:1f9b840af387532bd295de7df4962e11edcb619954305adb36e30ea7c20a42c7}
    issuer: ${SPRING_JWT_ISSUER:legalease}
    access-exp-min: ${SPRING_JWT_ACCESS_EXP_MIN:30}
    refresh-exp-min: ${SPRING_JWT_REFRESH_EXP_MIN:1440}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    show-details: always